import Vue from 'vue'
import Router from 'vue-router'


Vue.use(Router)

const routes=[
  {
    path:'/login',
    name:'login',
    component:()=>import('@/pages/Login.vue'),
    meta:{
      keepAlive:false
    }
  },
  {
    path:'/regist',
    name:'regist',
    component:()=>import('@/pages/Regist.vue'),
    meta:{
      keepAlive:false
    }
  },
  {
    path:'/aplyVolunte',
    name:'AplyVolunteer',
    component:()=>import('@/pages/AplyVolunteer.vue'),
    meta:{
      requireAuth:true,
      keepAlive:false
    }
  },
  {
    path:'/shop',
    name:'shop',
    component:()=>import('@/pages/Shop.vue'),
    meta:{
      requireAuth:true,
      keepAlive:false
    }
  },
  {
    path:'/shop/:goodsId',
    name:'shopInfo',
    component:()=>import('@/pages/ShopInfo.vue'),
    meta:{
      requireAuth:true,
      keepAlive:false
    }
  },
  {
    path:'/scoreInfo',
    name:'scoreInfo',
    component:()=>import('@/pages/ScoreInfo.vue'),
    meta:{
      requireAuth:true,
      keepAlive:false
    }
  },
  {
    path:'/record',
    name:'record',
    component:()=>import('@/pages/RecordList.vue'),
    meta:{
      requireAuth:true,
      keepAlive:false
    }
  },
  {
    path:'/volunTeam',
    name:'volunTeam',
    component:()=>import('@/pages/volunTeam.vue'),
    meta:{
      requireAuth:true,
      keepAlive:false
    }
  },
  {
    path:'/message',
    name:'message',
    component:()=>import('@/pages/Message.vue'),
    meta:{
      requireAuth:true,
      keepAlive:false
    }
  },
  {
    path:'/active',
    name:'active',
    component:()=>import('@/pages/Actv.vue'),
    meta:{
      requireAuth:true,
      keepAlive:false
    }
  },
  {
    path:'/sign',
    name:'sign',
    component:()=>import('@/pages/Sign.vue'),
    meta:{
      requireAuth:true,
      keepAlive:false
    }
  },
  {
    path:'/appoint',
    name:'appoint',
    component:()=>import('@/pages/Appointment.vue'),
    meta:{
      requireAuth:true,
      keepAlive:false
    }
  },
  {
    path:'/wish',
    name:'wish',
    component:()=>import('@/pages/Wish.vue'),
    meta:{
      requireAuth:true,
      keepAlive:false
    }
  },
  {
    path:'/person',
    name:'person',
    component:()=>import('@/pages/PersonInfo.vue'),
    meta:{
      requireAuth:true,
      keepAlive:false
    }
  },
  {
    path:'/phone',
    name:'phone',
    component:()=>import('@/pages/ModifyPhone.vue'),
    meta:{
      requireAuth:true,
      keepAlive:false
    }
  },
  {
    path:'/password',
    name:'password',
    component:()=>import('@/pages/ModifyPwd.vue'),
    meta:{
      requireAuth:true,
      keepAlive:false
    }
  },
  {
    path:'/findPwd',
    name:'findPwd',
    component:()=>import('@/pages/FindPwd.vue'),
    meta:{
      requireAuth:false,
      keepAlive:false
    }
  },
  {
    path:'/recruit',
    name:'recruit',
    component:()=>import('@/pages/Recruit.vue'),
    meta:{
      requireAuth:true,
      keepAlive:true
    }
  },
  {
    path:'/mien',
    name:'mien',
    component:()=>import('@/pages/Mien.vue'),
    meta:{
      requireAuth:true,
      keepAlive:false
    }
  },
  {
    path:'/actvInfo/:actvId',
    name:'actvInfo',
    component:()=>import('@/pages/ActvInfo.vue'),
    meta:{
      requireAuth:true,
      keepAlive:true,
      lastPath:""
    }
  },
  {
    path:'/apply/:actvId/:actvName',
    name:'apply',
    component:()=>import('@/pages/Apply.vue'),
    meta:{
      requireAuth:true,
      keepAlive:true
    }
  },
  {
    path:'/publish',
    name:'publish',
    component:()=>import('@/pages/Publish.vue'),
    meta:{
      requireAuth:true,
      keepAlive:false
    }
  },
  {
    path:'/subscribe/:sourceId',
    name:'subscribe',
    component:()=>import('@/pages/Subscribe.vue'),
    meta:{
      requireAuth:true,
      keepAlive:false
    }
  },
  {
    path:'/sourceList',
    name:'sourceList',
    component:()=>import('@/pages/SourceList.vue'),
    meta:{
      requireAuth:true,
      keepAlive:false
    }
  },
  {
    path:'/sourceInfo/:sourceId',
    name:'sourceInfo',
    component:()=>import('@/pages/SourceInfo.vue'),
    meta:{
      requireAuth:true,
      keepAlive:false
    }
  },
  {
    path:'/wishList',
    name:'wishList',
    component:()=>import('@/pages/WishList.vue'),
    meta:{
      requireAuth:true,
      keepAlive:false
    }
  },
  {
    path:'/wishInfo/:wishId',
    name:'wishInfo',
    component:()=>import('@/pages/WishInfo.vue'),
    meta:{
      requireAuth:true,
      keepAlive:true,
      lastPath:""
    }
  },
  {
    path:'/voteList',
    name:'voteList',
    component:()=>import('@/pages/VoteList.vue'),
    meta:{
      requireAuth:true,
      keepAlive:false
    }
  },
  {
    path:'/main',
    name:'mains',
    component:()=>import('@/pages/Main.vue'),
    meta:{
      keepAlive:false
    },
    children:[
      {
        path:'/main/center',
        name:'center',
        component:()=>import('@/pages/Center.vue'),
        meta:{
          requireAuth:true,
          keepAlive:false
        }
      },
      {
        path:'/main/hunger',
        name:'hunger',
        component:()=>import('@/pages/Hunger.vue'),
        meta:{
          requireAuth:true,
          keepAlive:true
        }
      },
      {
        path:'/main/desire',
        name:'desire',
        component:()=>import('@/pages/Desire.vue'),
        meta:{
          requireAuth:true,
          keepAlive:true
        }
      },
      {
        path:'/main/:id',
        name:'blank',
        component:()=>import('@/pages/Blank.vue'),
        meta:{
          keepAlive:false
        }
      },
      {
        path:'/main',
        redirect:'/main/center'
      }
    ]
  },
  {
    path:'/*',
    redirect:localStorage.getItem('appToken')?'/main/center':'/regist'
  },
  // {
  //   path:'/*',
  //   redirect:'/main/center'
  // }
]
export default new Router({
  mode:'hash',
  routes 
})


